# Generated by Django 4.0.2 on 2022-02-06 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Location latitude. Must be expressed in decimal degrees.')),
                ('longitude', models.FloatField(help_text='Location longitude. Must be expressed in decimal degrees.')),
                ('altitude', models.FloatField(help_text='Location longitude. Must be expressed in meters.')),
                ('date', models.DateTimeField(help_text='Location date.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.PROTECT, related_name='locations_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
