# Generated by Django 4.0.2 on 2022-02-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houmers', '0003_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='max_latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='max_longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='min_latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='min_longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
